### ISSUE TITLE
how to generate treeview class in sidebar menu

### ISSUE THREAD

**Issue by wilsonxyz** [bmsrox/baseapp-yii2basic-adminlte#1]
Hi,
i want to generate sidebar menu like this
`<li class="treeview">
              <a href="#">
                <i class="fa fa-folder"></i> <span>Jenis</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                  <li><a href="<?= Url::to(['/pph']) ?>"><i class="fa fa-circle-o"></i> Pph</a></li>
                  <li><a href="<?= Url::to(['/pks']) ?>"><i class="fa fa-circle-o"></i> PKS</a></li>
                  <li><a href="<?= Url::to(['/uang-bongkar']) ?>"><i class="fa fa-circle-o"></i> Uang Bongkar</a></li>
              </ul>
            </li>`
but i don't how to do this.
please advice. thanks.

**Comment by bmsrox** [comment]
Hi,

 Are you using Menu Widget?? if your answer yes, make just it
`['label' => 'Menu', 'url'=>'#', 'options'=>['class'=>'treeview'], 'items'=>[
    ['label'=>'Submenu', 'url'=>['/path/to/something']],
]],`

**Comment by wilsonxyz** [comment]
but inside this, there are 2 class more in order to make the treeview work.
